### ISSUE TITLE
question

### ISSUE THREAD

**Issue by infinitecry** [lilongweidev/GoodWeather#1]
你好，我在按照你的文章搭建MVP框架时，在KnifeKit类中import butterknife.ButterKnife和butterknife.Unbinder失败了，理由是cannot resolve symbol ButterKnife，请问我该如何解决这个问题？

**Comment by lilongweidev** [comment]
你这是添加依赖失败，绑定view异常，首先你要就看你的AndroidStudio有没有安装这个插件，然后在你的工程的build.gradle里面有没有添加依赖。

**Comment by infinitecry** [comment]
你好我最后在自己手机上测试的时候显示和风api的key是invalid的，我申请的是Android SDK的key，请问是出现了什么问题？



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "chenxi"<notifications@github.com&gt;; 
发送时间: 2020年4月26日(星期天) 上午10:34
收件人: "lilongweidev/GoodWeather"<GoodWeather@noreply.github.com&gt;; 
抄送: "水天之间"<315670761@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [lilongweidev/GoodWeather] question (#1)





 
你这是添加依赖失败，绑定view异常，首先你要就看你的AndroidStudio有没有安装这个插件，然后在你的工程的build.gradle里面有没有添加依赖。

**Comment by lilongweidev** [comment]
因为我用的不是Android SDK 的key，而是Web API 的key,用Android SDK的key的话需要在项目中添加和风SDK，并且集成进来。

**Comment by infinitecry** [comment]
emmm我用Web API的key试了一下，结果第一次闪退第二次显示invalid param，是因为我加天气的图标的方式不对吗

**Comment by lilongweidev** [comment]
invalid param  说明你是 无效的参数，检查你传递的参数是否正确、完整，还有你得告诉我先现在在写那个功能，对应第几篇文章，天气图标修改是我今天才写好的文章，是第十一篇

**Comment by infinitecry** [comment]
谢谢您的文章，我看了以后受益很大，我刚刚debug了，是传的参数类型有问题，现在正常了，谢谢您的解答

**Comment by lilongweidev** [comment]
能解决问题就最好，祝你好运！
