### ISSUE TITLE
小小的建议

### ISSUE THREAD

**Issue by lalala-feifei** [lilongweidev/GoodWeather#2]
要是可以查询历史天气就更完美了

**Comment by lilongweidev** [comment]
是一个不错的想法，和风的确提供了历史天气的API，不过是需要付费的。当然也可以写一个本地的历史天气存储表，保存最早10天前的天气，但是那样会有局限性，第一你必须每天打开一次这个软件，使它获取当前的数据然后报存起来。存满十条后删除最早的一条数据再存新数据，第二只能局限于你当前定位和自己手动切换的城市的历史天气，第三，天气这种数据历史的已经没有任何意义了，只是单纯的浪费资源，我想这也是和风要收费的主要原因吧。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lilongweidev/GoodWeather"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月14日(星期四) 晚上9:31
收件人:&nbsp;"lilongweidev/GoodWeather"<GoodWeather@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[lilongweidev/GoodWeather] 小小的建议 (#2)





 
要是可以查询历史天气就更完美了
