### ISSUE TITLE
您好，安装好了您提供的APP后显示查询城市失败（超过访问次数或余额不足），是怎么回事呢

### ISSUE THREAD

**Issue by GaoMingyue0118** [lilongweidev/GoodWeather#5]

**Comment by lilongweidev** [comment]
在天气APP第一篇文章我就说了，建议开发者是用自己的的天气ApiKey，因为我的被很多人使用，而每天的使用是有上限的，用完就访问天气接口就会提示这个，自己申请一个自己使用就行了。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年5月9日(周二) 下午5:51
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [lilongweidev/GoodWeather]您好，安装好了您提供的APP后显示查询城市失败（超过访问次数或余额不足），是怎么回事呢

**Comment by GaoMingyue0118** [comment]
> 

好的，谢谢您的回复

**Comment by lilongweidev** [comment]
Over
